---
タッチ:
  x: 65
  "y": 2
  z: 362
wait:
  x: 155.000000
  "y": 4.000000
  z: 353.000000
  world: lobby
world: world
chest:
  適当1:
    x: 258
    "y": 13
    z: 224
  適当3:
    x: 257
    "y": 13
    z: 226
  うほ:
    x: 199
    "y": 13
    z: 224
  s:
    x: 64
    "y": 1
    z: 357
spawns:
  s1:
    x: "0"
    "y": "4"
    z: "0"
  s2:
    x: "0"
    "y": "4"
    z: "0"
  s3:
    x: "0"
    "y": "4"
    z: "0"
  s5:
    x: "0"
    "y": "4"
    z: "0"
dispawn:
  x: "0"
  "y": "4"
  z: "0"
SaveConfigMessage: "false"
spawn:
  x: "0"
  "y": "4"
  z: "0"
最低人数: "3"
最大人数: "8"
待ち時間(s): "60"
...
